# Numpy 增删改查

In [5]:
import numpy as np

# 新增
n1 = np.arange(9).reshape([3, 3])
n2 = np.arange(9).reshape([3, 3])
print(n1)
print(n2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
# 垂直增加
print(np.hstack((n1, n2)))
print('------ hstack ------')
# 水平增加
print(np.vstack((n1, n2)))
print('------ vstack ------')

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]
------ hstack ------
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
------ vstack ------


In [3]:
# 删除
n3 = np.arange(9).reshape([3, 3])
print(n3)
print('------ n3 ------')
# 删除索引为 2 的一列
print(np.delete(n3, 2, axis=0))
print('------ n3 delete ------')
# 删除索引为 1 的行
print(np.delete(n3, 1, axis=1))
print('------ n3 delete ------')
# 删除索引为 1 2 的行
print(np.delete(n3, (1, 2), axis=1))
print('------ n3 delete ------')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------ n3 ------
[[0 1 2]
 [3 4 5]]
------ n3 delete ------
[[0 2]
 [3 5]
 [6 8]]
------ n3 delete ------
[[0]
 [3]
 [6]]
------ n3 delete ------


In [4]:
# 修改
n4 = np.arange(4).reshape(2, 2)
print(n4)
print('------ n4 ------')
# 修改二行的值
n4[1] = [0, 0]
print(n4)
print('------ n4 ------')
# 修改具体的值
n4[1, 1] = 5
print(n4)
print('------ n4 ------')

[[0 1]
 [2 3]]
------ n4 ------
[[0 1]
 [0 0]]
------ n4 ------
[[0 1]
 [0 5]]
------ n4 ------


In [6]:
# 查询
# where
n5 = np.arange(10)
print(n5)
# 大于 5 的值改为 2，否则改为 0
print(np.where(n5 > 5, 2, 0))
print('------ n5 ------')

# 不指定值，则输出元素的坐标
print(np.where(n5 > 5))

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 2 2 2 2]
------ n5 ------
(array([6, 7, 8, 9], dtype=int64),)
