# 维度处理

In [7]:
import numpy as np

# 重塑 reshape，不改变原数组
n1 = np.arange(9)
n2 = n1.reshape([3, 3])
print(n1)
print(n2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# 拉平，不改变原数组
print(n2.ravel())

[0 1 2 3 4 5 6 7 8]


In [4]:
# resize ， 会改变原数组
n2.resize((1, 9))
print(n2)

[[0 1 2 3 4 5 6 7 8]]


In [8]:
# 转置 T、transpose()，不改变元素组，
n3 = np.arange(6).reshape([2, 3])
print(n3)
print(n3.T)
print(n3.T.transpose())

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 1 2]
 [3 4 5]]


In [9]:
# split 切
n5 = np.arange(9)
print(np.hsplit(n5, 3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
