# NumPy 运算

## 加减乘除

In [8]:
import numpy as np

n1 = np.array([1, 2])
n2 = np.array([3, 4])
print(n1 + n2)
print(n1 - n2)
print(n1 * n2)
print(n1 / n2)

[4 6]
[-2 -2]
[3 8]
[0.33333333 0.5       ]


In [3]:
# +=
n2 += n1
print(n2)

[ 5 14]


In [4]:
# *=
n2 *= n1
print(n2)

[ 5 28]


In [5]:
# ** 幂运算
n3 = np.array([1, 2])
n4 = np.array([3, 4])
print(n3 ** n4)  # [1, 16]  1^3 2^4

[ 1 16]


In [6]:
# 标量运算
# 标量：单独的数； 向量：一组数； 标量运算理解为：向量和标量之间的运算，比如把一组数由 m 单位换成 km，那么需要把一组数除以一个数（1000）
n3 = np.linspace(1000, 9000, num=9, dtype=int)
print(n3 / 1000)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [9]:
# 比较运算
n5 = np.array([1, 2])
n6 = np.array([3, 4])
print(n5 > n6)  # [False False]
print(n5 == n6)  # [False False]
print(n5 <= n6)  # [True True]
print(n5 != n6)  # [True True]

[False False]
[False False]
[ True  True]
[ True  True]


In [10]:
A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
B = np.array([[5, 6], [7, 8]])  # 2x2 matrix
"""
1 2   5 6
3 4   7 8

1 * 5 + 2 * 7 = 19
1 * 6 + 2 * 8 = 22
3 * 5 + 4 * 7 = 43
3 * 6 + 4 * 8 = 50
"""
# 矩阵乘
print(A @ B)
print(A.dot(B))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
