# Numpy 处理函数

## 数学运算

In [17]:
import numpy as np

n1 = np.arange(9).reshape(3, 3)
n2 = np.full([3], 6)

print(n1)
print(n2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 6 6]


In [4]:
print(np.add(n1, n2))

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [5]:
print(np.subtract(n1, n2))

[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]


In [18]:
print(np.multiply(n1, n2))

[[ 0  6 12]
 [18 24 30]
 [36 42 48]]


In [7]:
print(np.divide(n1, n2))

[[0.         0.16666667 0.33333333]
 [0.5        0.66666667 0.83333333]
 [1.         1.16666667 1.33333333]]


In [8]:
# 倒数 x => 1/x
print(np.reciprocal(n2, dtype=float))

[0.16666667 0.16666667 0.16666667]


In [9]:
# 求幂 power
print(np.power(n2, 3))

[216 216 216]


In [10]:
# 取余 mod
print(np.mod(n2, 3))

[0 0 0]


In [11]:
# 四舍五入 round(a, decimals) ：decimals 保留位数
n3 = np.full([3], 6.666)
print(np.round(n3, 2))

[6.67 6.67 6.67]


In [12]:
# 向上取整 ceil
print(np.ceil(n3))

[7. 7. 7.]


In [13]:
# 向下取整 floor
print(np.floor(n3))

[6. 6. 6.]


In [14]:
# 三角函数
n = np.array([0, 30, 45, 60, 90])
print(np.sin(n * np.pi / 180))
print(np.cos(n * np.pi / 180))
print(np.tan(n * np.pi / 180))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [15]:
sin = np.sin(n * np.pi / 180)
inv = np.arcsin(sin)
print(inv)
print(np.degrees(inv))

[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[ 0. 30. 45. 60. 90.]


## 聚合函数

In [28]:
import numpy as np

n0 = np.array([[1, 2, 3], [2, 3, 4]])
print(n0)

[[1 2 3]
 [2 3 4]]


In [20]:
print(n0.sum())
print(n0.sum(axis=0))
print(n0.sum(axis=1))

15
[3 5 7]
[6 9]


In [22]:
print(n0.mean())
print(n0.mean(axis=0))

2.5
[1.5 2.5 3.5]


In [23]:
print(n0.max())
print(n0.max(axis=0))

4
[2 3 4]


In [24]:
print(n0.min(axis=0))

[1 2 3]


In [25]:
# 加权平均数
# 比如平均成绩为  70 80 90 ，每个成绩的权重值为 0.2 0.5 0.3，那么计算方法为  70*0.2 + 80*0.5 + 90*0.3= 81
# 然后再拿 81 / (权重和 0.2 + 0.5 + 0.3) = 81，那么加权平均值为 81
score = np.array([70, 80, 90])
weight = np.array([0.2, 0.5, 0.3])
print(np.average(score, weights=weight))

81.0


In [26]:
# 中位数
nums = np.array([1, 2, 3, 4, 7, 11, 15, 17, 19])
print(np.median(nums))

7.0


In [27]:
# 方差
print(np.var(nums))
# 标准差
print(np.std(nums))

42.39506172839506
6.5111490328816055


## 排序

In [33]:
import numpy as np

n1 = np.array([[4, 1, 3], [9, 4, 6], [7, 2, 3]])

print(n1)

[[4 1 3]
 [9 4 6]
 [7 2 3]]


In [30]:
print(np.sort(n1))
print(np.sort(n1, axis=0))  # 按列排序
print(np.sort(n1, axis=1))  # 按行排序

[[1 3 4]
 [4 6 9]
 [2 3 7]]
[[4 1 3]
 [7 2 3]
 [9 4 6]]
[[1 3 4]
 [4 6 9]
 [2 3 7]]


In [31]:
# argsort 返回数组从小到大排序的索引值
n2 = np.array([1, 3, 2, 5, 4])
sorted = np.argsort(n2)
print(n2)
print(sorted)
print(n2[sorted])

[1 3 2 5 4]
[0 2 1 4 3]
[1 2 3 4 5]


In [32]:
# 某重点高中，精英班录取学生按照总成绩录取
# 由于名额有限，因此当总成绩相同时，数学成绩高的优先录取
# 当总成绩和数学成绩都相同时，按照英语成绩高的优先录取
# 下面使用 lexsort() 函数对学生成绩进行排序，程序代码如下

math = np.array([101, 109, 115, 108, 118, 118])
en = np.array([117, 105, 118, 108, 98, 109])
total = np.array([621, 623, 620, 620, 615, 615])
sort_total = np.lexsort((en, math, total))
print('排序后的索引值')
print(sort_total)
print('通过排序后的索引获取排序后的数组：')
print(np.array([[en[i], math[i], total[i]] for i in sort_total]))

排序后的索引值
[4 5 3 2 0 1]
通过排序后的索引获取排序后的数组：
[[ 98 118 615]
 [109 118 615]
 [108 108 620]
 [118 115 620]
 [117 101 621]
 [105 109 623]]
