# 矩阵

## 矩阵创建

In [1]:
import numpy as np

# mat 只适用于 2 维矩阵
m1 = np.mat('1 2;3 4')
print(m1)
print(type(m1))  # <class 'numpy.matrix'>

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [2]:
m2 = np.mat([[1, 2], [3, 4]])
print(m2)

[[1 2]
 [3 4]]


In [3]:
# zeros
m3 = np.mat(np.zeros([3, 3]), dtype=int)
print(m3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# ones
m4 = np.mat(np.ones([3, 3]), dtype=int)
print(m4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
# rand
m5 = np.mat(np.random.randint(1, 5, [3, 3]), dtype=int)
print(m5)

[[2 2 2]
 [2 3 1]
 [3 2 3]]


In [7]:
# 创建对角矩阵：一个主对角线之外的元素皆为 0 的矩阵
m6 = np.mat(np.eye(4, 4, dtype=int))
print(m6)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [9]:
# 指定对角线的值
line = [1, 2, 3]
m7 = np.mat(np.diag(line))
print(m7)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


## 矩阵运算

In [11]:
# +
data1 = np.mat([[1, 2], [3, 4], [5, 6]])
data2 = np.mat([1, 2])
# 相加后会把 data1 每行加上 [1 2]
print(data1 + data2)

[[2 4]
 [4 6]
 [6 8]]


In [13]:
# -
print(data1 - data2)

[[0 0]
 [2 2]
 [4 4]]


In [14]:
# /
print(data1 / data2)

[[1. 1.]
 [3. 2.]
 [5. 3.]]


In [15]:
# *
data3 = np.mat([[1, 2], [3, 4]])
print(data1 * data3)

[[ 7 10]
 [15 22]
 [23 34]]
