# Numpy 切片

In [1]:
import numpy as np

# index
n1 = np.random.randint(1, 10, [3, 3])
print(n1)
# 获取第一列
print(n1[0])
# 获取第一列中的第二个值
print(n1[0][1])
print(n1[0, 1])

# slice
# 获取前两列
print(n1[0:2])
# start stop step
print(n1[0:2:2])

[[9 6 6]
 [8 7 8]
 [5 4 5]]
[9 6 6]
6
6
[[9 6 6]
 [8 7 8]]
[[9 6 6]]
