# ndarray 创建

## 基于 `array()` 创建

In [19]:
import numpy as np

# 创建一个一维数组
print(np.array([1, 2, 3]))

# 创建一个二维数组
print(np.array([[1, 2, 3], [4, 5, 6]]))

# 创建时指定类型
print(np.array([1, 2, 3], dtype='float64'))

# 复制其他 arr，为 True 时是深拷贝
n1 = np.array([1, 2, 3])
n2 = np.array(n1, copy=True)
n2[0] = 0
print(n1)
print(n2)
print(n1 is n2)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1. 2. 3.]
[1 2 3]
[0 2 3]
False


## 基于其他函数创建

In [33]:
import numpy as np

# empty 指定维度，数据自动初始化
print(np.empty((2, 2), dtype=int))

# zeros 以 0 填充
print(np.zeros((2, 2), dtype=int))

# ones 以 1 填充
print(np.ones((2, 2), dtype=int))

# full 指定值填充
print(np.full((2, 2), 8))

# arange 创建一维数组
print(np.arange(5))

# arange 创建二维数组 (起始值，终止值（不包含），步长)
print(np.arange(1, 12, 2))

# linspace 创建等差数列 (开始，结束，num= 样本数，endpoint=True 时包含结束值，retstep=True 显示等差的值，dtype 数据类型)
print(np.linspace(1000, 5000, 5, endpoint=True, retstep=True, dtype=int))

# logspace 创建等比数列 (开始，结束，num= 样本数，endpoint=True 时包含结束值，base= 对数 log 的底数，dtype 数据类型)
print(np.logspace(0, 8, 8, endpoint=True, base=2, dtype='uint64'))

[[8 8]
 [8 8]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[8 8]
 [8 8]]
[0 1 2 3 4]
[ 1  3  5  7  9 11]
(array([1000, 2000, 3000, 4000, 5000]), 1000.0)
[  1   2   4  10  23  52 115 256]


## 基于 `random` 创建

In [39]:
import numpy as np

# random 是 0 到 1 内的随机数，生成 1 维 5 个元素的数组
print(np.random.rand(5))

# rand 创建二维数组
print(np.random.rand(2, 2))

# randn 创建正态分布数组
print(np.random.rand(5))

# randint 指定 ([开始，结束)，shape)
print(np.random.randint(1, 5, [2,2]))

# normal 生成正态分布 (loc: 均值，scale：标准差， shape)
print(np.random.normal(0, 1, 10))

[0.49933445 0.25789985 0.7709461  0.88632022 0.66079473]
[[0.40549156 0.24371261]
 [0.76029083 0.75490587]]
[0.36208055 0.75896354 0.50381058 0.36587041 0.85884969]
[[1 4]
 [1 2]]
[ 0.93761091 -0.61297726 -0.15666239 -0.16290555  0.67845923  1.51978211
 -0.15657815  0.58629744  1.37165846 -0.59374147]


## 基于其它数组创建

In [44]:
import numpy as np

# fromiter(iter, dtype, count=-1 读取多少个元素) 用于从可迭代对象中创建
iter = (x * 2 for x in range(10))
print(np.fromiter(iter, dtype='int'))

# frombuffer(buffer, dtype, count=-1, offset=0)：buffer 实现了 __buffer__ 的对象； count 读取多少数据；offset 从哪里开始读
print(np.frombuffer(b'helloworld', dtype='S1'))

# empty_like：创建一个给定数组和它相同维度和数据类型，并且未初始化的的数组
# 注意：函数创建的数组中的元素值是未知的，并且会受到之前分配给该内存块的值的影响
n1 = np.full((3, 3), 10)
print(np.empty_like(n1, dtype='int8'))

# zeros_like
print(np.zeros_like(n1, dtype='int8'))

# ones_like
print(np.ones_like(n1, dtype='int8'))

# full_like
print(np.full_like(n1, 6, dtype='int8'))


[ 0  2  4  6  8 10 12 14 16 18]
[b'h' b'e' b'l' b'l' b'o' b'w' b'o' b'r' b'l' b'd']
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
