# NumPy 数据类型

NumPy 中 `dtype` 指的是数组元素的数据类型。以下是 NumPy 支持的一些数据类型：
- `bool_`：布尔类型
- `int_`：默认整数，相当于 c 中的 long，通常为 int32
- `intc`：相当于 c 的 int，通常为 int32
- `intp`：用于索引的整数，相当于 c 的 size_t，通常为 int64
- 带数字 `int`：int8、int16、int32、int64、uint8...
- `float_`：_float64 缩写
- 带数字 `float`：float16、float32、float64
- `complex`: 复数，默认为双精度 64 位

# ndarray 属性

ndarray 属性：
- ndim：维度
- shape：每个维度的长度
- size：总元素个数
- dtype：类型
- itemsize：每个元素占用的存储空间，字节数
- data：存储 array 的内存地址，一般使用索引来访问，所以用不到该属性

In [5]:
import numpy as np

n1 = np.arange(15).reshape(3, 5)
print(n1)

print('dim:', n1.ndim)
print('shape:', n1.shape)
print('size:', n1.size)
print('dtype:', n1.dtype)
print('itemsize:', n1.itemsize)
print('data:', n1.data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
dim: 2
shape: (3, 5)
size: 15
dtype: int32
itemsize: 4
data: <memory at 0x000002B1A73C7A00>
